config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  
  get 'courses' => "pages#courses" 
  get 'locations' => "pages#locations"
  get 'about' => "pages#about"
  get 'contact' => "pages#contact"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def courses
  end

  def locations
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mygcd</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'shared/navbar' %>
	<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<% provide(:title, "About") %>
<!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
        <h1>About Griffith!</h1>
        <h3>Griffith College is Ireland's leading private college with campuses in Cork, Dublin and Limerick</h3>        
      </div>
    </div>

    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2>Welcome from the President</h2>
          <p>Griffith College prides itself on the graduates we have produced over the past 40 years. These ambitious, enterprising and talented young men and women have carved out notable careers across a diverse range of industries. </p>
          <em>Prof Diarmuid Hegarty<br />
          President of Griffith College</em>
        </div>
        <div class="col-md-4">
          <h2>Wide variety of amenities and facilities on your doorstep</h2>
          <p>With over 7,000 students at its campuses in Dublin, Cork and Limerick, Griffith College is the ideal choice for students seeking a strong education and a vibrant college life. Each campus is centrally located, meaning you have a wide variety of amenities and facilities on your doorstep, and with a large selection of clubs and societies, from football and basketball to film and photography, there are plenty of ways to get to know your fellow students!</p>
       </div>
        <div class="col-md-4">
          <h2>Game Room</h2>
          <p><%= image_tag("RelaxingPlayingPool.png") %></p>
        </div>
      </div>

app/views/pages/contact.html.erb
<% provide(:title, "Contact") %>
<div class="container">
	<div class="jumbotron">
        <h1>Contact Us</h1>
        <p>
        	Do you have a query about one of our courses? Call or Email any of our campuses and we’ll be delighted to assist.
        </p>
      </div>
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2>Dublin Campus</h2>
          	<p>
          		Griffith College Dublin,<br />
				South Circular Road,<br />
				Dublin 8, <br />
				Dublin.
			</p>
			<p>
				<strong>Phone:</strong> +353 1 415 04 00 <br />
				<%= mail_to "admission@gcd.ie" do %>
  					<strong>Email: </strong> <span>admission@gcd.ie</span>
				<% end %>
			</p>
        </div>
        <div class="col-md-4">
         	<h2>Cork campus</h2>
          	<p>
	          	Griffith College Cork,<br />
				Wellington Road,<br />
				Cork.
			</p>
			<p>
				<strong>Phone:</strong> +353 21 4507027<br />
				<%= mail_to "admission@gcc.ie" do %>
  					<strong>Email: </strong> <span>admission@gcc.ie</span>
				<% end %>
			</p>
       </div>
        <div class="col-md-4">
          	<h2>Limerick</h2>
          	<p>
          		Griffith College Limerick,<br />
				O'Connell Avenue,<br />
				Limerick City,<br />
				Limerick.
			</p>
			<p>	
				<strong>Phone: </strong>+353 61 310031<br />
				<%= mail_to "admission@gcl.ie" do %>
  					<strong>Email: </strong> <span>admission@gcl.ie</span>
				<% end %>
			</p>
        </div>
      </div>

app/views/pages/courses.html.erb
<% provide(:title, "Courses") %>
<div class="jumbotron">
    <div class="container">
        <h1>Find a Course</h1>
        <h4>
        	Check out the wide range of courses that we offer at Griffith College’s from undergraduate, postgraduate and short courses.
        </h4>        
    </div>
</div>
<div class="row marketing">
	<div class="col-lg-1"></div>
	<div class="col-lg-5">
        <h2>ACCA (Association of Chartered Certified Accountants)</h2>
		<h3>Professional</h3>
		<p>
			ACCA for the February-June 2015 term will begin during week commencing 16th February 2015. Timetables are available on our website.
		</p>
		<strong>Cork:</strong> <em>Full-Time, Part-Time, Online</em><br/>
		<strong>Dublin:</strong> <em>Full-Time, Part-Time, Online</em><br/>
		<strong>Limerick:</strong> <em>Full-Time, Part-Time, Online</em>
          
        <h2>MBA in International Business<h2>
		<h3>Postgraduate</h3>
		<p>
			This programme is designed to prepare graduates for careers in international business. It provides an innovative route to an internationally recognised MBA qualification
		</p>
		<strong>Dublin:</strong> <em>Full-Time, Part-Time</em>
    </div>

    <div class="col-lg-5">
        <h2>BA (Hons) in Accounting & Finance</h2>
		<h3>Undergraduate</h3>
		<h4>Study Abroad</h4>
		<p>
			The programme gives you an understanding of the legal, business and social environments in which accountancy operates and enables you to be conversant in the technical languages.
		</p>
		<strong>Cork:</strong> <em>Full-Time, Part-Time</em><br/>
		<strong>Dublin:</strong> <em>Full-Time, Part-Time</em><br/>
		<strong>Limerick:</strong> <em>Full-Time, Part-Time</em>

        <h2>AutoCAD 3D Advanced</h2>
		<h3>Short Course</h3>
		<p>
			This part-time evening course was designed for participants looking to develop their skill in drafting procedures to create and modify new or existing 3D objects.
		</p>
		<strong>Dublin:</strong> <em>Part-Time</em>
	</div>
    <div class="col-lg-1"></div>
</div>

app/views/pages/home.html.erb
<% provide(:title, "Home") %>
<div class="container">

      <div class="row row-offcanvas row-offcanvas-right">

        <div class="col-xs-12 col-sm-9">
          <p class="pull-right visible-xs">
            <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Toggle nav</button>
          </p>
          <div class="jumbotron">
            <h1>Study at Griffith College – Dublin, Cork and Limerick</h1>
            <p>Establish in 1974 Griffith is a home to over 7,000 students.</p>
          </div>
          <div class="row">
            <div class="col-xs-6 col-lg-4">
              <h2>News</h2>
              <h4>GCD student takes First Prize</h4>
              <p>GCD fourth year student takes the first award at the Business Grad annual event</p>
            </div><!--/.col-xs-6.col-lg-4-->
            <div class="col-xs-6 col-lg-4">
              <h2>Events</h2>
              <p>Student inspired Teacher's Hero award voting starts today. Remember to vote for your teacher hero!</p>              
            </div><!--/.col-xs-6.col-lg-4-->
            <div class="col-xs-6 col-lg-4">
              <h2>Testimonials</h2>
              <p>Griffith provides me with support and resources that I need in order to accomplish my studies</p>              
            </div><!--/.col-xs-6.col-lg-4-->
            
          </div><!--/row-->
        </div><!--/.col-xs-12.col-sm-9-->

        <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar">
          <div class="list-group">
            <ul class="nav nav-pills">
	  			<li role="presentation"><%= link_to "Courses", courses_path %></li>	  			
	  		</ul>
	  		<ul class="nav nav-pills">	  			
	  			<li role="presentation"><%= link_to "Locations", locations_path %></li>
	  		</ul>
          </div>
        </div><!--/.sidebar-offcanvas-->
      </div><!--/row-->

      <hr>

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div><!--/.container-->

app/views/pages/locations.html.erb
<% provide(:title, "Locations") %>
<!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
        <h1>Our Campuses!</h1>
        <h4>
        	Established in 1974, Griffith College provides a wide range of full and part-time certificate, diploma, degree and postgraduate courses and is home to over 7,000 students. Our campuses are easily accessible via car and public transport and centrally located within each city, so you have a wide range of amenities on your doorstep. Each campus has its own unique history and character. For more information on our locations in Cork, Dublin and Limerick please choose from the options below.
        </h4>        
      </div>
    </div>

    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2>Dublin</h2>
          <p>
          	Welcome to Griffith College’s Dublin campus, home to Ireland’s largest independent third level college with over 7,000 students. Located in the heart of Dublin City, this 7 acre campus has a heritage dating back over 200 years. Here you will find information on our courses, faculty teams, campus facilities, and all the latest news and events taking place at GCD.
          </p>
          <p><%= image_tag("dublincampus.jpg") %></p>
        </div>
        <div class="col-md-4">
          <h2>Cork</h2>
          <p>
          	GRIFFITH COLLEGE CORK (GCC) Skerry’s has been at the forefront of education in Cork since 1884, and has a long history of providing quality education. The College campus is located on Wellington Road, just a fifteen minutes walk from St. Patrick’s Street, the main shopping street in Cork city centre. It is approximately five hundred metres from the main train station serving a wide variety of towns and cities. The main bus station is a fifteen minute walk from the College and most bus routes start and terminate there.
          </p>
          <p><%= image_tag("corkcampus.png") %></p>
       </div>
        <div class="col-md-4">
          <h2>Limerick</h2>
          <p>
          	Located in in the heart of Limerick students enjoy all of the amenities and facilities available to students in the city centre. The college provides a wide range of internationally recognised full-time and part-time courses. All courses are taught from a state-of-the-art facility on O’Connell Avenue. Our track record for excellence is demonstrated in the many prize-winners and successful graduates the College produces each year.
          </p>
          <p><%= image_tag("limerickcampus.png") %></p>
        </div>
      </div>

app/views/shared/_navbar.html.erb
<div class="header clearfix">
	<h3 class="text-muted"><%= image_tag("GCD.jpg") %></h3>
<nav class="navbar navbar-inverse">
	<ul class="nav nav-pills">
	  <li role="presentation" class="active"><%= link_to "Home", root_path %></li>
	  <li role="presentation"><%= link_to "Courses", courses_path %></li>
	  <li role="presentation"><%= link_to "Locations", locations_path %></li>
	  <li role="presentation"><%= link_to "About", about_path %></li>
	  <li role="presentation"><%= link_to "Contact", contact_path %></li>
	</ul>
</nav>

</div>
